// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class TC1Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void tC1() {
    driver.Navigate().GoToUrl("https://www.adobe.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1379, 934);
    {
      var element = driver.FindElement(By.Id("gnav_746"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.LinkText("Sign In")).Click();
    driver.FindElement(By.Id("EmailPage-EmailField")).SendKeys("tonycontinue@gmail.com");
    driver.FindElement(By.Id("EmailPage-EmailField")).SendKeys(Keys.Enter);
    driver.FindElement(By.Id("PasswordPage-PasswordField")).SendKeys("Ansxogns123");
    driver.FindElement(By.Id("PasswordPage-PasswordField")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector("#id-61699d4650fd8d8f3b1920bc022ae05d b")).Click();
    driver.FindElement(By.Id("marquee")).Click();
    Assert.That(driver.FindElement(By.CssSelector("#id-61699d4650fd8d8f3b1920bc022ae05d h1")).Text, Is.EqualTo("Welcome back, TAEHOON."));
  }
}
